version: "3.8"

services:
  app:
    build: .
    container_name: student4-3-app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - .env
    extra_hosts:
    - "host.docker.internal:host-gateway"
    restart: always